apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogsvc-deployment
  namespace: nagp-ns
  labels:
    app: productcatalogsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogsvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: productcatalogsvc
    spec:
      containers:
        - name: productcatalogsvc
          image: CONTAINER_IMAGE
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsNonRoot: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024"
              cpu: "700m"
          ports:
            - containerPort: 8050
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xms512m -Xmx1536m -XX:+ExitOnOutOfMemoryError
          envFrom:
            - secretRef:
                name: hilton-gen2-es
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8050
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5