apiVersion: v1
kind: Service
metadata:
  name: productcatalogsvc
  namespace: nagp-ns
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8050
      targetPort: 8050
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30050